<Project>
	<PropertyGroup>
		<BaluVersion Condition="'$(BaluVersion)' == ''">0.6.1</BaluVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'Balu' Or
						  '$(MSBuildProjectName)' == 'bc' Or
						  '$(MSBuildProjectName)' == 'bi' Or
						  '$(MSBuildProjectName)' == 'Balu.Interpretation' Or
						  '$(MSBuildProjectName)' == 'Balu.Sdk'">
		<Version>$(BaluVersion)</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
	</PropertyGroup>
</Project>
