using TestHelpers;
using Xunit;

namespace Balu.Tests.CompilationTests.ExecutionTests;

public partial class ExecutionTests
{
    [Theory]
    [InlineData("1 [&] true", "BL1002: Binary operator '&' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [&] 2", "BL1002: Binary operator '&' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [&&] true", "BL1002: Binary operator '&&' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [&&] 2", "BL1002: Binary operator '&&' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [&&] 2", "BL1002: Binary operator '&&' cannot be applied to types 'int' and 'int'.")]
    [InlineData("1 [|] true", "BL1002: Binary operator '|' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [|] 2", "BL1002: Binary operator '|' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [||] true", "BL1002: Binary operator '||' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [||] 2", "BL1002: Binary operator '||' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [||] 2", "BL1002: Binary operator '||' cannot be applied to types 'int' and 'int'.")]
    [InlineData("1 [^] true", "BL1002: Binary operator '^' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [^] 2", "BL1002: Binary operator '^' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [+] true", "BL1002: Binary operator '+' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [+] 2", "BL1002: Binary operator '+' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("true [+] false", "BL1002: Binary operator '+' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [-] true", "BL1002: Binary operator '-' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [-] 2", "BL1002: Binary operator '-' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("true [-] false", "BL1002: Binary operator '-' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [*] true", "BL1002: Binary operator '*' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [*] 2", "BL1002: Binary operator '*' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("true [*] false", "BL1002: Binary operator '*' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [/] true", "BL1002: Binary operator '/' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [/] 2", "BL1002: Binary operator '/' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("true [/] false", "BL1002: Binary operator '/' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [==] true", "BL1002: Binary operator '==' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [==] 2", "BL1002: Binary operator '==' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [!=] true", "BL1002: Binary operator '!=' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [!=] 2", "BL1002: Binary operator '!=' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("1 [<] true", "BL1002: Binary operator '<' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [<] 2", "BL1002: Binary operator '<' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("false [<] true", "BL1002: Binary operator '<' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [<=] true", "BL1002: Binary operator '<=' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [<=] 2", "BL1002: Binary operator '<=' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("false [<=] true", "BL1002: Binary operator '<=' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [>] true", "BL1002: Binary operator '>' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [>] 2", "BL1002: Binary operator '>' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("false [>] true", "BL1002: Binary operator '>' cannot be applied to types 'bool' and 'bool'.")]
    [InlineData("1 [>=] true", "BL1002: Binary operator '>=' cannot be applied to types 'int' and 'bool'.")]
    [InlineData("false [>=] 2", "BL1002: Binary operator '>=' cannot be applied to types 'bool' and 'int'.")]
    [InlineData("false [>=] true", "BL1002: Binary operator '>=' cannot be applied to types 'bool' and 'bool'.")]
    public void Script_BinaryOperator_Reports_TypeMismatch(string code, string? diagnostics) => code.AssertScriptEvaluation(diagnostics);
}
