<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Balu.Interpretation</RootNamespace>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Balu\Balu.csproj" />
	</ItemGroup>

</Project>
